name: Post Instagram Story Weekly

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  post-story:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install instagrapi

    - name: Run script
      env:
        IG_USERNAME: ${{ secrets.BURNER_USERNAME }}  # Access username from secrets
        IG_PASSWORD: ${{ secrets.BURNER_PASSWORD }}  # Access password from secrets
        
      run: |
        echo "Running Instagram story poster..."
        python post_story.py  # Runs your script
